/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authImport } from './routes/__auth'
import { Route as IndexImport } from './routes/index'
import { Route as EngineerIndexImport } from './routes/engineer/index'
import { Route as CscIndexImport } from './routes/csc/index'
import { Route as EngineerStockReturnImport } from './routes/engineer/stock-return'
import { Route as EngineerStockReportImport } from './routes/engineer/stock-report'
import { Route as EngineerStockReceiveImport } from './routes/engineer/stock-receive'
import { Route as EngineerFaultyReturnImport } from './routes/engineer/faulty-return'
import { Route as EngineerDefectiveReportImport } from './routes/engineer/defective-report'
import { Route as CscScrapReportImport } from './routes/csc/scrap-report'
import { Route as CscPurchaseReturnImport } from './routes/csc/purchase-return'
import { Route as CscAgingReportImport } from './routes/csc/aging-report'
import { Route as CscAdminOptionsImport } from './routes/csc/admin-options'
import { Route as authLoginImport } from './routes/__auth/login'
import { Route as CscDefectiveIndexImport } from './routes/csc/defective/index'
import { Route as CscChallanIndexImport } from './routes/csc/challan/index'
import { Route as CscStockTransferImport } from './routes/csc/stock/transfer'
import { Route as CscStockReceiveImport } from './routes/csc/stock/receive'
import { Route as CscStockOwnImport } from './routes/csc/stock/own'
import { Route as CscStockBranchImport } from './routes/csc/stock/branch'
import { Route as CscStockApprovalImport } from './routes/csc/stock/approval'
import { Route as CscJobEntrySummaryImport } from './routes/csc/job/entry-summary'
import { Route as CscJobEntryListImport } from './routes/csc/job/entry-list'
import { Route as CscJobEntryImport } from './routes/csc/job/entry'
import { Route as CscEngineerTransferReportImport } from './routes/csc/engineer/transfer-report'
import { Route as CscEngineerStockImport } from './routes/csc/engineer/stock'
import { Route as CscEngineerReturnImport } from './routes/csc/engineer/return'
import { Route as CscEngineerFaultyImport } from './routes/csc/engineer/faulty'
import { Route as CscEngineerDefectiveImport } from './routes/csc/engineer/defective'
import { Route as CscChallanChallanIdImport } from './routes/csc/challan/$challanId'
import { Route as CscAdminOptionsUsersImport } from './routes/csc/admin-options/users'
import { Route as CscAdminOptionsStockEntryImport } from './routes/csc/admin-options/stock-entry'
import { Route as CscAdminOptionsSkuCodeImport } from './routes/csc/admin-options/sku-code'
import { Route as CscAdminOptionsBranchImport } from './routes/csc/admin-options/branch'
import { Route as CscStockFaultyIndexImport } from './routes/csc/stock/faulty/index'
import { Route as CscStockFaultyReportImport } from './routes/csc/stock/faulty/report'

// Create/Update Routes

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EngineerIndexRoute = EngineerIndexImport.update({
  id: '/engineer/',
  path: '/engineer/',
  getParentRoute: () => rootRoute,
} as any)

const CscIndexRoute = CscIndexImport.update({
  id: '/csc/',
  path: '/csc/',
  getParentRoute: () => rootRoute,
} as any)

const EngineerStockReturnRoute = EngineerStockReturnImport.update({
  id: '/engineer/stock-return',
  path: '/engineer/stock-return',
  getParentRoute: () => rootRoute,
} as any)

const EngineerStockReportRoute = EngineerStockReportImport.update({
  id: '/engineer/stock-report',
  path: '/engineer/stock-report',
  getParentRoute: () => rootRoute,
} as any)

const EngineerStockReceiveRoute = EngineerStockReceiveImport.update({
  id: '/engineer/stock-receive',
  path: '/engineer/stock-receive',
  getParentRoute: () => rootRoute,
} as any)

const EngineerFaultyReturnRoute = EngineerFaultyReturnImport.update({
  id: '/engineer/faulty-return',
  path: '/engineer/faulty-return',
  getParentRoute: () => rootRoute,
} as any)

const EngineerDefectiveReportRoute = EngineerDefectiveReportImport.update({
  id: '/engineer/defective-report',
  path: '/engineer/defective-report',
  getParentRoute: () => rootRoute,
} as any)

const CscScrapReportRoute = CscScrapReportImport.update({
  id: '/csc/scrap-report',
  path: '/csc/scrap-report',
  getParentRoute: () => rootRoute,
} as any)

const CscPurchaseReturnRoute = CscPurchaseReturnImport.update({
  id: '/csc/purchase-return',
  path: '/csc/purchase-return',
  getParentRoute: () => rootRoute,
} as any)

const CscAgingReportRoute = CscAgingReportImport.update({
  id: '/csc/aging-report',
  path: '/csc/aging-report',
  getParentRoute: () => rootRoute,
} as any)

const CscAdminOptionsRoute = CscAdminOptionsImport.update({
  id: '/csc/admin-options',
  path: '/csc/admin-options',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRoute,
} as any)

const CscDefectiveIndexRoute = CscDefectiveIndexImport.update({
  id: '/csc/defective/',
  path: '/csc/defective/',
  getParentRoute: () => rootRoute,
} as any)

const CscChallanIndexRoute = CscChallanIndexImport.update({
  id: '/csc/challan/',
  path: '/csc/challan/',
  getParentRoute: () => rootRoute,
} as any)

const CscStockTransferRoute = CscStockTransferImport.update({
  id: '/csc/stock/transfer',
  path: '/csc/stock/transfer',
  getParentRoute: () => rootRoute,
} as any)

const CscStockReceiveRoute = CscStockReceiveImport.update({
  id: '/csc/stock/receive',
  path: '/csc/stock/receive',
  getParentRoute: () => rootRoute,
} as any)

const CscStockOwnRoute = CscStockOwnImport.update({
  id: '/csc/stock/own',
  path: '/csc/stock/own',
  getParentRoute: () => rootRoute,
} as any)

const CscStockBranchRoute = CscStockBranchImport.update({
  id: '/csc/stock/branch',
  path: '/csc/stock/branch',
  getParentRoute: () => rootRoute,
} as any)

const CscStockApprovalRoute = CscStockApprovalImport.update({
  id: '/csc/stock/approval',
  path: '/csc/stock/approval',
  getParentRoute: () => rootRoute,
} as any)

const CscJobEntrySummaryRoute = CscJobEntrySummaryImport.update({
  id: '/csc/job/entry-summary',
  path: '/csc/job/entry-summary',
  getParentRoute: () => rootRoute,
} as any)

const CscJobEntryListRoute = CscJobEntryListImport.update({
  id: '/csc/job/entry-list',
  path: '/csc/job/entry-list',
  getParentRoute: () => rootRoute,
} as any)

const CscJobEntryRoute = CscJobEntryImport.update({
  id: '/csc/job/entry',
  path: '/csc/job/entry',
  getParentRoute: () => rootRoute,
} as any)

const CscEngineerTransferReportRoute = CscEngineerTransferReportImport.update({
  id: '/csc/engineer/transfer-report',
  path: '/csc/engineer/transfer-report',
  getParentRoute: () => rootRoute,
} as any)

const CscEngineerStockRoute = CscEngineerStockImport.update({
  id: '/csc/engineer/stock',
  path: '/csc/engineer/stock',
  getParentRoute: () => rootRoute,
} as any)

const CscEngineerReturnRoute = CscEngineerReturnImport.update({
  id: '/csc/engineer/return',
  path: '/csc/engineer/return',
  getParentRoute: () => rootRoute,
} as any)

const CscEngineerFaultyRoute = CscEngineerFaultyImport.update({
  id: '/csc/engineer/faulty',
  path: '/csc/engineer/faulty',
  getParentRoute: () => rootRoute,
} as any)

const CscEngineerDefectiveRoute = CscEngineerDefectiveImport.update({
  id: '/csc/engineer/defective',
  path: '/csc/engineer/defective',
  getParentRoute: () => rootRoute,
} as any)

const CscChallanChallanIdRoute = CscChallanChallanIdImport.update({
  id: '/csc/challan/$challanId',
  path: '/csc/challan/$challanId',
  getParentRoute: () => rootRoute,
} as any)

const CscAdminOptionsUsersRoute = CscAdminOptionsUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CscAdminOptionsRoute,
} as any)

const CscAdminOptionsStockEntryRoute = CscAdminOptionsStockEntryImport.update({
  id: '/stock-entry',
  path: '/stock-entry',
  getParentRoute: () => CscAdminOptionsRoute,
} as any)

const CscAdminOptionsSkuCodeRoute = CscAdminOptionsSkuCodeImport.update({
  id: '/sku-code',
  path: '/sku-code',
  getParentRoute: () => CscAdminOptionsRoute,
} as any)

const CscAdminOptionsBranchRoute = CscAdminOptionsBranchImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => CscAdminOptionsRoute,
} as any)

const CscStockFaultyIndexRoute = CscStockFaultyIndexImport.update({
  id: '/csc/stock/faulty/',
  path: '/csc/stock/faulty/',
  getParentRoute: () => rootRoute,
} as any)

const CscStockFaultyReportRoute = CscStockFaultyReportImport.update({
  id: '/csc/stock/faulty/report',
  path: '/csc/stock/faulty/report',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authImport
    }
    '/csc/admin-options': {
      id: '/csc/admin-options'
      path: '/csc/admin-options'
      fullPath: '/csc/admin-options'
      preLoaderRoute: typeof CscAdminOptionsImport
      parentRoute: typeof rootRoute
    }
    '/csc/aging-report': {
      id: '/csc/aging-report'
      path: '/csc/aging-report'
      fullPath: '/csc/aging-report'
      preLoaderRoute: typeof CscAgingReportImport
      parentRoute: typeof rootRoute
    }
    '/csc/purchase-return': {
      id: '/csc/purchase-return'
      path: '/csc/purchase-return'
      fullPath: '/csc/purchase-return'
      preLoaderRoute: typeof CscPurchaseReturnImport
      parentRoute: typeof rootRoute
    }
    '/csc/scrap-report': {
      id: '/csc/scrap-report'
      path: '/csc/scrap-report'
      fullPath: '/csc/scrap-report'
      preLoaderRoute: typeof CscScrapReportImport
      parentRoute: typeof rootRoute
    }
    '/engineer/defective-report': {
      id: '/engineer/defective-report'
      path: '/engineer/defective-report'
      fullPath: '/engineer/defective-report'
      preLoaderRoute: typeof EngineerDefectiveReportImport
      parentRoute: typeof rootRoute
    }
    '/engineer/faulty-return': {
      id: '/engineer/faulty-return'
      path: '/engineer/faulty-return'
      fullPath: '/engineer/faulty-return'
      preLoaderRoute: typeof EngineerFaultyReturnImport
      parentRoute: typeof rootRoute
    }
    '/engineer/stock-receive': {
      id: '/engineer/stock-receive'
      path: '/engineer/stock-receive'
      fullPath: '/engineer/stock-receive'
      preLoaderRoute: typeof EngineerStockReceiveImport
      parentRoute: typeof rootRoute
    }
    '/engineer/stock-report': {
      id: '/engineer/stock-report'
      path: '/engineer/stock-report'
      fullPath: '/engineer/stock-report'
      preLoaderRoute: typeof EngineerStockReportImport
      parentRoute: typeof rootRoute
    }
    '/engineer/stock-return': {
      id: '/engineer/stock-return'
      path: '/engineer/stock-return'
      fullPath: '/engineer/stock-return'
      preLoaderRoute: typeof EngineerStockReturnImport
      parentRoute: typeof rootRoute
    }
    '/csc/': {
      id: '/csc/'
      path: '/csc'
      fullPath: '/csc'
      preLoaderRoute: typeof CscIndexImport
      parentRoute: typeof rootRoute
    }
    '/engineer/': {
      id: '/engineer/'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerIndexImport
      parentRoute: typeof rootRoute
    }
    '/csc/admin-options/branch': {
      id: '/csc/admin-options/branch'
      path: '/branch'
      fullPath: '/csc/admin-options/branch'
      preLoaderRoute: typeof CscAdminOptionsBranchImport
      parentRoute: typeof CscAdminOptionsImport
    }
    '/csc/admin-options/sku-code': {
      id: '/csc/admin-options/sku-code'
      path: '/sku-code'
      fullPath: '/csc/admin-options/sku-code'
      preLoaderRoute: typeof CscAdminOptionsSkuCodeImport
      parentRoute: typeof CscAdminOptionsImport
    }
    '/csc/admin-options/stock-entry': {
      id: '/csc/admin-options/stock-entry'
      path: '/stock-entry'
      fullPath: '/csc/admin-options/stock-entry'
      preLoaderRoute: typeof CscAdminOptionsStockEntryImport
      parentRoute: typeof CscAdminOptionsImport
    }
    '/csc/admin-options/users': {
      id: '/csc/admin-options/users'
      path: '/users'
      fullPath: '/csc/admin-options/users'
      preLoaderRoute: typeof CscAdminOptionsUsersImport
      parentRoute: typeof CscAdminOptionsImport
    }
    '/csc/challan/$challanId': {
      id: '/csc/challan/$challanId'
      path: '/csc/challan/$challanId'
      fullPath: '/csc/challan/$challanId'
      preLoaderRoute: typeof CscChallanChallanIdImport
      parentRoute: typeof rootRoute
    }
    '/csc/engineer/defective': {
      id: '/csc/engineer/defective'
      path: '/csc/engineer/defective'
      fullPath: '/csc/engineer/defective'
      preLoaderRoute: typeof CscEngineerDefectiveImport
      parentRoute: typeof rootRoute
    }
    '/csc/engineer/faulty': {
      id: '/csc/engineer/faulty'
      path: '/csc/engineer/faulty'
      fullPath: '/csc/engineer/faulty'
      preLoaderRoute: typeof CscEngineerFaultyImport
      parentRoute: typeof rootRoute
    }
    '/csc/engineer/return': {
      id: '/csc/engineer/return'
      path: '/csc/engineer/return'
      fullPath: '/csc/engineer/return'
      preLoaderRoute: typeof CscEngineerReturnImport
      parentRoute: typeof rootRoute
    }
    '/csc/engineer/stock': {
      id: '/csc/engineer/stock'
      path: '/csc/engineer/stock'
      fullPath: '/csc/engineer/stock'
      preLoaderRoute: typeof CscEngineerStockImport
      parentRoute: typeof rootRoute
    }
    '/csc/engineer/transfer-report': {
      id: '/csc/engineer/transfer-report'
      path: '/csc/engineer/transfer-report'
      fullPath: '/csc/engineer/transfer-report'
      preLoaderRoute: typeof CscEngineerTransferReportImport
      parentRoute: typeof rootRoute
    }
    '/csc/job/entry': {
      id: '/csc/job/entry'
      path: '/csc/job/entry'
      fullPath: '/csc/job/entry'
      preLoaderRoute: typeof CscJobEntryImport
      parentRoute: typeof rootRoute
    }
    '/csc/job/entry-list': {
      id: '/csc/job/entry-list'
      path: '/csc/job/entry-list'
      fullPath: '/csc/job/entry-list'
      preLoaderRoute: typeof CscJobEntryListImport
      parentRoute: typeof rootRoute
    }
    '/csc/job/entry-summary': {
      id: '/csc/job/entry-summary'
      path: '/csc/job/entry-summary'
      fullPath: '/csc/job/entry-summary'
      preLoaderRoute: typeof CscJobEntrySummaryImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/approval': {
      id: '/csc/stock/approval'
      path: '/csc/stock/approval'
      fullPath: '/csc/stock/approval'
      preLoaderRoute: typeof CscStockApprovalImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/branch': {
      id: '/csc/stock/branch'
      path: '/csc/stock/branch'
      fullPath: '/csc/stock/branch'
      preLoaderRoute: typeof CscStockBranchImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/own': {
      id: '/csc/stock/own'
      path: '/csc/stock/own'
      fullPath: '/csc/stock/own'
      preLoaderRoute: typeof CscStockOwnImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/receive': {
      id: '/csc/stock/receive'
      path: '/csc/stock/receive'
      fullPath: '/csc/stock/receive'
      preLoaderRoute: typeof CscStockReceiveImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/transfer': {
      id: '/csc/stock/transfer'
      path: '/csc/stock/transfer'
      fullPath: '/csc/stock/transfer'
      preLoaderRoute: typeof CscStockTransferImport
      parentRoute: typeof rootRoute
    }
    '/csc/challan/': {
      id: '/csc/challan/'
      path: '/csc/challan'
      fullPath: '/csc/challan'
      preLoaderRoute: typeof CscChallanIndexImport
      parentRoute: typeof rootRoute
    }
    '/csc/defective/': {
      id: '/csc/defective/'
      path: '/csc/defective'
      fullPath: '/csc/defective'
      preLoaderRoute: typeof CscDefectiveIndexImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/faulty/report': {
      id: '/csc/stock/faulty/report'
      path: '/csc/stock/faulty/report'
      fullPath: '/csc/stock/faulty/report'
      preLoaderRoute: typeof CscStockFaultyReportImport
      parentRoute: typeof rootRoute
    }
    '/csc/stock/faulty/': {
      id: '/csc/stock/faulty/'
      path: '/csc/stock/faulty'
      fullPath: '/csc/stock/faulty'
      preLoaderRoute: typeof CscStockFaultyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface authRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteChildren: authRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface CscAdminOptionsRouteChildren {
  CscAdminOptionsBranchRoute: typeof CscAdminOptionsBranchRoute
  CscAdminOptionsSkuCodeRoute: typeof CscAdminOptionsSkuCodeRoute
  CscAdminOptionsStockEntryRoute: typeof CscAdminOptionsStockEntryRoute
  CscAdminOptionsUsersRoute: typeof CscAdminOptionsUsersRoute
}

const CscAdminOptionsRouteChildren: CscAdminOptionsRouteChildren = {
  CscAdminOptionsBranchRoute: CscAdminOptionsBranchRoute,
  CscAdminOptionsSkuCodeRoute: CscAdminOptionsSkuCodeRoute,
  CscAdminOptionsStockEntryRoute: CscAdminOptionsStockEntryRoute,
  CscAdminOptionsUsersRoute: CscAdminOptionsUsersRoute,
}

const CscAdminOptionsRouteWithChildren = CscAdminOptionsRoute._addFileChildren(
  CscAdminOptionsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof authRouteWithChildren
  '/login': typeof authLoginRoute
  '/csc/admin-options': typeof CscAdminOptionsRouteWithChildren
  '/csc/aging-report': typeof CscAgingReportRoute
  '/csc/purchase-return': typeof CscPurchaseReturnRoute
  '/csc/scrap-report': typeof CscScrapReportRoute
  '/engineer/defective-report': typeof EngineerDefectiveReportRoute
  '/engineer/faulty-return': typeof EngineerFaultyReturnRoute
  '/engineer/stock-receive': typeof EngineerStockReceiveRoute
  '/engineer/stock-report': typeof EngineerStockReportRoute
  '/engineer/stock-return': typeof EngineerStockReturnRoute
  '/csc': typeof CscIndexRoute
  '/engineer': typeof EngineerIndexRoute
  '/csc/admin-options/branch': typeof CscAdminOptionsBranchRoute
  '/csc/admin-options/sku-code': typeof CscAdminOptionsSkuCodeRoute
  '/csc/admin-options/stock-entry': typeof CscAdminOptionsStockEntryRoute
  '/csc/admin-options/users': typeof CscAdminOptionsUsersRoute
  '/csc/challan/$challanId': typeof CscChallanChallanIdRoute
  '/csc/engineer/defective': typeof CscEngineerDefectiveRoute
  '/csc/engineer/faulty': typeof CscEngineerFaultyRoute
  '/csc/engineer/return': typeof CscEngineerReturnRoute
  '/csc/engineer/stock': typeof CscEngineerStockRoute
  '/csc/engineer/transfer-report': typeof CscEngineerTransferReportRoute
  '/csc/job/entry': typeof CscJobEntryRoute
  '/csc/job/entry-list': typeof CscJobEntryListRoute
  '/csc/job/entry-summary': typeof CscJobEntrySummaryRoute
  '/csc/stock/approval': typeof CscStockApprovalRoute
  '/csc/stock/branch': typeof CscStockBranchRoute
  '/csc/stock/own': typeof CscStockOwnRoute
  '/csc/stock/receive': typeof CscStockReceiveRoute
  '/csc/stock/transfer': typeof CscStockTransferRoute
  '/csc/challan': typeof CscChallanIndexRoute
  '/csc/defective': typeof CscDefectiveIndexRoute
  '/csc/stock/faulty/report': typeof CscStockFaultyReportRoute
  '/csc/stock/faulty': typeof CscStockFaultyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof authRouteWithChildren
  '/login': typeof authLoginRoute
  '/csc/admin-options': typeof CscAdminOptionsRouteWithChildren
  '/csc/aging-report': typeof CscAgingReportRoute
  '/csc/purchase-return': typeof CscPurchaseReturnRoute
  '/csc/scrap-report': typeof CscScrapReportRoute
  '/engineer/defective-report': typeof EngineerDefectiveReportRoute
  '/engineer/faulty-return': typeof EngineerFaultyReturnRoute
  '/engineer/stock-receive': typeof EngineerStockReceiveRoute
  '/engineer/stock-report': typeof EngineerStockReportRoute
  '/engineer/stock-return': typeof EngineerStockReturnRoute
  '/csc': typeof CscIndexRoute
  '/engineer': typeof EngineerIndexRoute
  '/csc/admin-options/branch': typeof CscAdminOptionsBranchRoute
  '/csc/admin-options/sku-code': typeof CscAdminOptionsSkuCodeRoute
  '/csc/admin-options/stock-entry': typeof CscAdminOptionsStockEntryRoute
  '/csc/admin-options/users': typeof CscAdminOptionsUsersRoute
  '/csc/challan/$challanId': typeof CscChallanChallanIdRoute
  '/csc/engineer/defective': typeof CscEngineerDefectiveRoute
  '/csc/engineer/faulty': typeof CscEngineerFaultyRoute
  '/csc/engineer/return': typeof CscEngineerReturnRoute
  '/csc/engineer/stock': typeof CscEngineerStockRoute
  '/csc/engineer/transfer-report': typeof CscEngineerTransferReportRoute
  '/csc/job/entry': typeof CscJobEntryRoute
  '/csc/job/entry-list': typeof CscJobEntryListRoute
  '/csc/job/entry-summary': typeof CscJobEntrySummaryRoute
  '/csc/stock/approval': typeof CscStockApprovalRoute
  '/csc/stock/branch': typeof CscStockBranchRoute
  '/csc/stock/own': typeof CscStockOwnRoute
  '/csc/stock/receive': typeof CscStockReceiveRoute
  '/csc/stock/transfer': typeof CscStockTransferRoute
  '/csc/challan': typeof CscChallanIndexRoute
  '/csc/defective': typeof CscDefectiveIndexRoute
  '/csc/stock/faulty/report': typeof CscStockFaultyReportRoute
  '/csc/stock/faulty': typeof CscStockFaultyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__auth': typeof authRouteWithChildren
  '/__auth/login': typeof authLoginRoute
  '/csc/admin-options': typeof CscAdminOptionsRouteWithChildren
  '/csc/aging-report': typeof CscAgingReportRoute
  '/csc/purchase-return': typeof CscPurchaseReturnRoute
  '/csc/scrap-report': typeof CscScrapReportRoute
  '/engineer/defective-report': typeof EngineerDefectiveReportRoute
  '/engineer/faulty-return': typeof EngineerFaultyReturnRoute
  '/engineer/stock-receive': typeof EngineerStockReceiveRoute
  '/engineer/stock-report': typeof EngineerStockReportRoute
  '/engineer/stock-return': typeof EngineerStockReturnRoute
  '/csc/': typeof CscIndexRoute
  '/engineer/': typeof EngineerIndexRoute
  '/csc/admin-options/branch': typeof CscAdminOptionsBranchRoute
  '/csc/admin-options/sku-code': typeof CscAdminOptionsSkuCodeRoute
  '/csc/admin-options/stock-entry': typeof CscAdminOptionsStockEntryRoute
  '/csc/admin-options/users': typeof CscAdminOptionsUsersRoute
  '/csc/challan/$challanId': typeof CscChallanChallanIdRoute
  '/csc/engineer/defective': typeof CscEngineerDefectiveRoute
  '/csc/engineer/faulty': typeof CscEngineerFaultyRoute
  '/csc/engineer/return': typeof CscEngineerReturnRoute
  '/csc/engineer/stock': typeof CscEngineerStockRoute
  '/csc/engineer/transfer-report': typeof CscEngineerTransferReportRoute
  '/csc/job/entry': typeof CscJobEntryRoute
  '/csc/job/entry-list': typeof CscJobEntryListRoute
  '/csc/job/entry-summary': typeof CscJobEntrySummaryRoute
  '/csc/stock/approval': typeof CscStockApprovalRoute
  '/csc/stock/branch': typeof CscStockBranchRoute
  '/csc/stock/own': typeof CscStockOwnRoute
  '/csc/stock/receive': typeof CscStockReceiveRoute
  '/csc/stock/transfer': typeof CscStockTransferRoute
  '/csc/challan/': typeof CscChallanIndexRoute
  '/csc/defective/': typeof CscDefectiveIndexRoute
  '/csc/stock/faulty/report': typeof CscStockFaultyReportRoute
  '/csc/stock/faulty/': typeof CscStockFaultyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/csc/admin-options'
    | '/csc/aging-report'
    | '/csc/purchase-return'
    | '/csc/scrap-report'
    | '/engineer/defective-report'
    | '/engineer/faulty-return'
    | '/engineer/stock-receive'
    | '/engineer/stock-report'
    | '/engineer/stock-return'
    | '/csc'
    | '/engineer'
    | '/csc/admin-options/branch'
    | '/csc/admin-options/sku-code'
    | '/csc/admin-options/stock-entry'
    | '/csc/admin-options/users'
    | '/csc/challan/$challanId'
    | '/csc/engineer/defective'
    | '/csc/engineer/faulty'
    | '/csc/engineer/return'
    | '/csc/engineer/stock'
    | '/csc/engineer/transfer-report'
    | '/csc/job/entry'
    | '/csc/job/entry-list'
    | '/csc/job/entry-summary'
    | '/csc/stock/approval'
    | '/csc/stock/branch'
    | '/csc/stock/own'
    | '/csc/stock/receive'
    | '/csc/stock/transfer'
    | '/csc/challan'
    | '/csc/defective'
    | '/csc/stock/faulty/report'
    | '/csc/stock/faulty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/csc/admin-options'
    | '/csc/aging-report'
    | '/csc/purchase-return'
    | '/csc/scrap-report'
    | '/engineer/defective-report'
    | '/engineer/faulty-return'
    | '/engineer/stock-receive'
    | '/engineer/stock-report'
    | '/engineer/stock-return'
    | '/csc'
    | '/engineer'
    | '/csc/admin-options/branch'
    | '/csc/admin-options/sku-code'
    | '/csc/admin-options/stock-entry'
    | '/csc/admin-options/users'
    | '/csc/challan/$challanId'
    | '/csc/engineer/defective'
    | '/csc/engineer/faulty'
    | '/csc/engineer/return'
    | '/csc/engineer/stock'
    | '/csc/engineer/transfer-report'
    | '/csc/job/entry'
    | '/csc/job/entry-list'
    | '/csc/job/entry-summary'
    | '/csc/stock/approval'
    | '/csc/stock/branch'
    | '/csc/stock/own'
    | '/csc/stock/receive'
    | '/csc/stock/transfer'
    | '/csc/challan'
    | '/csc/defective'
    | '/csc/stock/faulty/report'
    | '/csc/stock/faulty'
  id:
    | '__root__'
    | '/'
    | '/__auth'
    | '/__auth/login'
    | '/csc/admin-options'
    | '/csc/aging-report'
    | '/csc/purchase-return'
    | '/csc/scrap-report'
    | '/engineer/defective-report'
    | '/engineer/faulty-return'
    | '/engineer/stock-receive'
    | '/engineer/stock-report'
    | '/engineer/stock-return'
    | '/csc/'
    | '/engineer/'
    | '/csc/admin-options/branch'
    | '/csc/admin-options/sku-code'
    | '/csc/admin-options/stock-entry'
    | '/csc/admin-options/users'
    | '/csc/challan/$challanId'
    | '/csc/engineer/defective'
    | '/csc/engineer/faulty'
    | '/csc/engineer/return'
    | '/csc/engineer/stock'
    | '/csc/engineer/transfer-report'
    | '/csc/job/entry'
    | '/csc/job/entry-list'
    | '/csc/job/entry-summary'
    | '/csc/stock/approval'
    | '/csc/stock/branch'
    | '/csc/stock/own'
    | '/csc/stock/receive'
    | '/csc/stock/transfer'
    | '/csc/challan/'
    | '/csc/defective/'
    | '/csc/stock/faulty/report'
    | '/csc/stock/faulty/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRoute: typeof authRouteWithChildren
  CscAdminOptionsRoute: typeof CscAdminOptionsRouteWithChildren
  CscAgingReportRoute: typeof CscAgingReportRoute
  CscPurchaseReturnRoute: typeof CscPurchaseReturnRoute
  CscScrapReportRoute: typeof CscScrapReportRoute
  EngineerDefectiveReportRoute: typeof EngineerDefectiveReportRoute
  EngineerFaultyReturnRoute: typeof EngineerFaultyReturnRoute
  EngineerStockReceiveRoute: typeof EngineerStockReceiveRoute
  EngineerStockReportRoute: typeof EngineerStockReportRoute
  EngineerStockReturnRoute: typeof EngineerStockReturnRoute
  CscIndexRoute: typeof CscIndexRoute
  EngineerIndexRoute: typeof EngineerIndexRoute
  CscChallanChallanIdRoute: typeof CscChallanChallanIdRoute
  CscEngineerDefectiveRoute: typeof CscEngineerDefectiveRoute
  CscEngineerFaultyRoute: typeof CscEngineerFaultyRoute
  CscEngineerReturnRoute: typeof CscEngineerReturnRoute
  CscEngineerStockRoute: typeof CscEngineerStockRoute
  CscEngineerTransferReportRoute: typeof CscEngineerTransferReportRoute
  CscJobEntryRoute: typeof CscJobEntryRoute
  CscJobEntryListRoute: typeof CscJobEntryListRoute
  CscJobEntrySummaryRoute: typeof CscJobEntrySummaryRoute
  CscStockApprovalRoute: typeof CscStockApprovalRoute
  CscStockBranchRoute: typeof CscStockBranchRoute
  CscStockOwnRoute: typeof CscStockOwnRoute
  CscStockReceiveRoute: typeof CscStockReceiveRoute
  CscStockTransferRoute: typeof CscStockTransferRoute
  CscChallanIndexRoute: typeof CscChallanIndexRoute
  CscDefectiveIndexRoute: typeof CscDefectiveIndexRoute
  CscStockFaultyReportRoute: typeof CscStockFaultyReportRoute
  CscStockFaultyIndexRoute: typeof CscStockFaultyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRoute: authRouteWithChildren,
  CscAdminOptionsRoute: CscAdminOptionsRouteWithChildren,
  CscAgingReportRoute: CscAgingReportRoute,
  CscPurchaseReturnRoute: CscPurchaseReturnRoute,
  CscScrapReportRoute: CscScrapReportRoute,
  EngineerDefectiveReportRoute: EngineerDefectiveReportRoute,
  EngineerFaultyReturnRoute: EngineerFaultyReturnRoute,
  EngineerStockReceiveRoute: EngineerStockReceiveRoute,
  EngineerStockReportRoute: EngineerStockReportRoute,
  EngineerStockReturnRoute: EngineerStockReturnRoute,
  CscIndexRoute: CscIndexRoute,
  EngineerIndexRoute: EngineerIndexRoute,
  CscChallanChallanIdRoute: CscChallanChallanIdRoute,
  CscEngineerDefectiveRoute: CscEngineerDefectiveRoute,
  CscEngineerFaultyRoute: CscEngineerFaultyRoute,
  CscEngineerReturnRoute: CscEngineerReturnRoute,
  CscEngineerStockRoute: CscEngineerStockRoute,
  CscEngineerTransferReportRoute: CscEngineerTransferReportRoute,
  CscJobEntryRoute: CscJobEntryRoute,
  CscJobEntryListRoute: CscJobEntryListRoute,
  CscJobEntrySummaryRoute: CscJobEntrySummaryRoute,
  CscStockApprovalRoute: CscStockApprovalRoute,
  CscStockBranchRoute: CscStockBranchRoute,
  CscStockOwnRoute: CscStockOwnRoute,
  CscStockReceiveRoute: CscStockReceiveRoute,
  CscStockTransferRoute: CscStockTransferRoute,
  CscChallanIndexRoute: CscChallanIndexRoute,
  CscDefectiveIndexRoute: CscDefectiveIndexRoute,
  CscStockFaultyReportRoute: CscStockFaultyReportRoute,
  CscStockFaultyIndexRoute: CscStockFaultyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__auth",
        "/csc/admin-options",
        "/csc/aging-report",
        "/csc/purchase-return",
        "/csc/scrap-report",
        "/engineer/defective-report",
        "/engineer/faulty-return",
        "/engineer/stock-receive",
        "/engineer/stock-report",
        "/engineer/stock-return",
        "/csc/",
        "/engineer/",
        "/csc/challan/$challanId",
        "/csc/engineer/defective",
        "/csc/engineer/faulty",
        "/csc/engineer/return",
        "/csc/engineer/stock",
        "/csc/engineer/transfer-report",
        "/csc/job/entry",
        "/csc/job/entry-list",
        "/csc/job/entry-summary",
        "/csc/stock/approval",
        "/csc/stock/branch",
        "/csc/stock/own",
        "/csc/stock/receive",
        "/csc/stock/transfer",
        "/csc/challan/",
        "/csc/defective/",
        "/csc/stock/faulty/report",
        "/csc/stock/faulty/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/login"
      ]
    },
    "/__auth/login": {
      "filePath": "__auth/login.tsx",
      "parent": "/__auth"
    },
    "/csc/admin-options": {
      "filePath": "csc/admin-options.tsx",
      "children": [
        "/csc/admin-options/branch",
        "/csc/admin-options/sku-code",
        "/csc/admin-options/stock-entry",
        "/csc/admin-options/users"
      ]
    },
    "/csc/aging-report": {
      "filePath": "csc/aging-report.tsx"
    },
    "/csc/purchase-return": {
      "filePath": "csc/purchase-return.tsx"
    },
    "/csc/scrap-report": {
      "filePath": "csc/scrap-report.tsx"
    },
    "/engineer/defective-report": {
      "filePath": "engineer/defective-report.tsx"
    },
    "/engineer/faulty-return": {
      "filePath": "engineer/faulty-return.tsx"
    },
    "/engineer/stock-receive": {
      "filePath": "engineer/stock-receive.tsx"
    },
    "/engineer/stock-report": {
      "filePath": "engineer/stock-report.tsx"
    },
    "/engineer/stock-return": {
      "filePath": "engineer/stock-return.tsx"
    },
    "/csc/": {
      "filePath": "csc/index.tsx"
    },
    "/engineer/": {
      "filePath": "engineer/index.tsx"
    },
    "/csc/admin-options/branch": {
      "filePath": "csc/admin-options/branch.tsx",
      "parent": "/csc/admin-options"
    },
    "/csc/admin-options/sku-code": {
      "filePath": "csc/admin-options/sku-code.tsx",
      "parent": "/csc/admin-options"
    },
    "/csc/admin-options/stock-entry": {
      "filePath": "csc/admin-options/stock-entry.tsx",
      "parent": "/csc/admin-options"
    },
    "/csc/admin-options/users": {
      "filePath": "csc/admin-options/users.tsx",
      "parent": "/csc/admin-options"
    },
    "/csc/challan/$challanId": {
      "filePath": "csc/challan/$challanId.tsx"
    },
    "/csc/engineer/defective": {
      "filePath": "csc/engineer/defective.tsx"
    },
    "/csc/engineer/faulty": {
      "filePath": "csc/engineer/faulty.tsx"
    },
    "/csc/engineer/return": {
      "filePath": "csc/engineer/return.tsx"
    },
    "/csc/engineer/stock": {
      "filePath": "csc/engineer/stock.tsx"
    },
    "/csc/engineer/transfer-report": {
      "filePath": "csc/engineer/transfer-report.tsx"
    },
    "/csc/job/entry": {
      "filePath": "csc/job/entry.tsx"
    },
    "/csc/job/entry-list": {
      "filePath": "csc/job/entry-list.tsx"
    },
    "/csc/job/entry-summary": {
      "filePath": "csc/job/entry-summary.tsx"
    },
    "/csc/stock/approval": {
      "filePath": "csc/stock/approval.tsx"
    },
    "/csc/stock/branch": {
      "filePath": "csc/stock/branch.tsx"
    },
    "/csc/stock/own": {
      "filePath": "csc/stock/own.tsx"
    },
    "/csc/stock/receive": {
      "filePath": "csc/stock/receive.tsx"
    },
    "/csc/stock/transfer": {
      "filePath": "csc/stock/transfer.tsx"
    },
    "/csc/challan/": {
      "filePath": "csc/challan/index.tsx"
    },
    "/csc/defective/": {
      "filePath": "csc/defective/index.tsx"
    },
    "/csc/stock/faulty/report": {
      "filePath": "csc/stock/faulty/report.tsx"
    },
    "/csc/stock/faulty/": {
      "filePath": "csc/stock/faulty/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
